" Jon Parise <jon@indelible.org>

set nocompatible

" Plugins
"
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
call plug#begin()
Plug 'croaker/mustang-vim'
Plug 'chriskempson/base16-vim'
Plug 'junegunn/seoul256.vim'
Plug 'kien/ctrlp.vim'
Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/syntastic'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/vader.vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-unimpaired'
Plug 'airblade/vim-gitgutter'
Plug 'justinmk/vim-dirvish'
Plug 'majutsushi/tagbar'
Plug 'mileszs/ack.vim'
Plug 'solarnz/arcanist.vim'
Plug 'elixir-lang/vim-elixir', {'for': 'elixir'}
Plug 'fatih/vim-go', {'for': 'go'}
Plug 'rodjek/vim-puppet', {'for': 'puppet'}
Plug 'solarnz/thrift.vim', {'for': 'thrift'}
Plug 'mitsuhiko/vim-jinja', {'for': 'html'}
Plug 'godlygeek/tabular' | Plug 'plasticboy/vim-markdown', {'for': 'markdown'}
Plug 'autowitch/hive.vim'
Plug 'raimon49/requirements.txt.vim'
Plug 'jvirtanen/vim-cocoapods'
Plug 'kergoth/vim-hilinks'
if v:version >= 704
    Plug 'ludovicchabant/vim-gutentags'
endif
call plug#end()

set autoindent          " turn autoindenting on
set autowrite           " auto-save before running external commands
set background=dark     " dark background
set nobackup            " turn backups off
set backspace=indent,eol,start " smarter backspace
set nocompatible        " turn off full vi compatibility
set cmdwinheight=3      " height of the command window
set completeopt=menu,longest,preview " insert mode completion options
set cpoptions=aABceF    " vi compatibility options
set directory=~/tmp,/tmp
set encoding=utf-8      " change the default text encoding
set esckeys             " allows cursor keys in insert mode
set noerrorbells        " turn off error bells
set esckeys             " allows cursor keys in insert mode
set expandtab           " expand tabs to spaces
set formatoptions+=nr   " options for "text format" ("gp")
set helpheight=0        " disable help
set hidden              " enable hidden buffers
set history=100         " remember the last 100 lines of command-line history
set nohlsearch          " turn off search result highlighting
set ignorecase          " mostly ignore case in search patterns. see smartcase
set incsearch           " use incremental search
set noinsertmode        " don't start vim in insertmode
set joinspaces          " insert two spaces after period when joining lines
set laststatus=2        " always show status line
set lazyredraw          " don't bother updating screen during macro playback
set nolist              " turn off extended character listing
set listchars=tab:»·,extends:›,precedes:‹,nbsp:␣,trail:·
set magic               " use extended regexp in search patterns
set modelines=0         " turn off modelines
set mouse=h             " mouse options
set mousehide           " hide the mouse in the gui
set nonumber            " don't number lines
set report=0            " show all changes
set ruler               " show cursor position
set scrolloff=3         " scroll when within 3 lines of the screen's edge
set shiftround          " round indent size to a multiple of shiftwidth
set shiftwidth=4        " number of spaces in each indent
set shortmess=atI       " abbreviate all messages
set showbreak=↪\        " show at the start of wrapped lines
set noshowcmd           " don't show incomplete commands
set showmode            " show the current mode
set showtabline=1       " show tabline as needed
set smartcase           " respect uppercase characters when searching
set smartindent         " smart indenting when starting a new line
set smarttab            " smart movement and deleting based on tab settings
set softtabstop=4       " set soft tab stop to four spaces
set splitbelow          " open horizontal splits below current window
set splitright          " open vertical splits to the right
set nostartofline       " don't jump to first char with page commands
set synmaxcol=800       " don't attempt to syntax highlight long lines
set tabstop=4           " set tabs to eight spaces
set textwidth=78        " set the maximum text width
set title               " turn on the titlebar
set t_vb=               " turn off terminal's visual bell
set updatetime=250      " speed up file sync frequency
set visualbell          " turn on the visual bell
set wildchar=<TAB>      " character used for command line expansion
set wildmenu            " use menu when in 'full' command-line completion mode
set wildmode=list:longest,full " completion mode behavior
set wrapmargin=0        " wrap from the right margin
set nowritebackup       " don't write backups

if has('linebreak') && exists('&breakindent')
    set breakindent                 " indent wrapped lines to match start
    if exists('&breakindentopt')
        set breakindentopt=shift:2  " emphasize broken lines by indenting them
    endif
endif

if v:version > 703 || v:version == 703 && has('patch541')
    set formatoptions+=j " remove comment leader when joining comment lines
endif

" Platform / GUI options
if has('gui_running')
    colorscheme base16-ocean
    set guioptions=aAeimgr
    set ruler
    set title

    if has('gui_macvim')
        silent! set guifont=Menlo\ Regular\ for\ Powerline:h14
        if &guifont == 'Menlo Regular for Powerline:h14'
            let g:airline_powerline_fonts = 1
        else
            set guifont=Menlo:h14
        endif
    elseif has('gui_win32')
        set guifont=Consolas:h10.5
    endif
elseif has('termguicolors')
    if $TERM_PROGRAM == "iTerm.app"
        let g:airline_powerline_fonts = 1
    endif

    set termguicolors
    colorscheme base16-ocean
else
    let g:loaded_airline = 1

    colorscheme mustang
    hi StatusLine term=bold,reverse ctermfg=236 ctermbg=252
    hi Todo ctermfg=9 ctermbg=234 term=standout
endif

" Autocommands
if has('autocmd')
    augroup MainAutocmds
        autocmd!

        " Open help in a vertical split
        autocmd FileType help wincmd L

        " Resize all windows when vim itself is resized
        autocmd VimResized * execute "normal! \<c-w>="
    augroup END
endif

" Ack (ag)
if executable('ag')
    set grepprg=ag\ --nogroup\ --nocolor\ --ignore-case\ --column\ --vimgrep
    set grepformat=%f:%l:%c:%m,%f:%l:%m
    let g:ackprg = 'ag --vimgrep'
    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

" Toggle fold at current position.
nnoremap <Tab> za

" Avoid unintentional switches to Ex mode.
nmap Q q

" Buffer management
map  <Right> :bnext<CR>
imap <Right> <ESC>:bnext<CR>
map  <Left> :bprev<CR>
imap <Left> <ESC>:bprev<CR>

" Reformat the current paragraph to textwidth
imap <C-J> <c-o>gqap
map  <C-J> gqap
