tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "bash"
brew "bash-completion"
brew "bat"
brew "ctags", args: ["HEAD"]
brew "curl"
brew "fd"
brew "fzf"
brew "mas"
brew "python"
brew "ripgrep"
brew "vim"

mas "Acorn", id: 1233861775
mas "Byword", id: 420212497
mas "DaisyDisk", id: 411643860
mas "Marked 2", id: 890031187
mas "Noizio", id: 928871589
mas "Soulver 2", id: 413965349
mas "WiFi Explorer", id: 494803304

cask "fliqlo"
cask "nvalt"

cask "font-fira-code"
cask "font-ibm-plex"
cask "font-input"
cask "font-lato"
cask 'font-roboto-mono'
cask "font-source-code-pro"
