[ -z "$PS1" ] && return

set -o notify

shopt -s checkwinsize
shopt -s extglob
shopt -s histappend

umask 0022

if [ -d "$HOME/Bin" ]; then
	PATH="$HOME/Bin:$PATH"
elif [ -d "$HOME/bin" ]; then
	PATH="$HOME/bin:$PATH"
fi

# Default to en_US locale with UTF-8 encoding.
: ${LANG:="en_US.UTF-8"}
: ${LANGUAGE:="en"}
: ${LC_CTYPE:="en_US.UTF-8"}
: ${LC_ALL:="en_US.UTF-8"}
export LANG LANGUAGE LC_CTYPE LC_ALL

HISTCONTROL=ignoreboth
HISTIGNORE="&:bg:fg"
PROMPT_DIRTRIM=3
PS1="[\W]\$ "

# Some shells let us configure their window title. Take advantage of that to
# display the current working directory. Remote (ssh) shels also include the
# hostname.
if [[ $TERM == "xterm"* ]]; then
	if [ -x "$SSH_CONNECTION" ]; then
		PS1="\[\e]0;\h:\w\a\]$PS1"
	else
		PS1="\[\e]0;\w\a\]$PS1"
	fi
fi

# Prefer foregrounded MacVim if it's available.
if [ -n "$(command -v mvim)" ]; then
	EDITOR='mvim -f'
	VISUAL='mvim -f'
else
	EDITOR=vim
	VISUAL=vim
fi
export EDITOR VISUAL

export PAGER=less
export MANPAGER='less -FiRs'
export LESS='-ErX'

export DIFF_OPTIONS='-du'
export GREP_OPTIONS='--binary-files=without-match'

stty werase undef
bind '"\C-w": unix-filename-rubout'

# Optionally include any local settings.
if [ -f $HOME/.bashrc.local ]; then
	. $HOME/.bashrc.local
fi
